name: build

on:
  push:
    branches: ["*"]
    pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git pkg-config libfuse2 \
          libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev \
          mesa-common-dev libgtk-3-dev libfreetype-dev libmpv-dev
      - name: Build ImPlay
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
          cmake --build . --target package
          make install DESTDIR=AppDir
          curl -LO https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          curl -LO https://raw.githubusercontent.com/linuxdeploy/linuxdeploy-plugin-gtk/master/linuxdeploy-plugin-gtk.sh
          chmod +x linuxdeploy-x86_64.AppImage linuxdeploy-plugin-gtk.sh
          cp ../resources/linux/implay.desktop .
          cp ../resources/icon.png implay.png
          DEPLOY_GTK_VERSION=3 ./linuxdeploy-x86_64.AppImage --appdir AppDir --plugin gtk --output appimage \
            --desktop-file implay.desktop --icon-file implay.png
          mv ImPlay-*.AppImage ImPlay-linux64.AppImage
      - uses: actions/upload-artifact@v3
        with:
          name: ImPlay-linux
          path: |
            build/ImPlay-*.AppImage
            build/ImPlay-*.deb
  macos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_INSTALL_CLEANUP: 1
        run: |
          brew update
          brew install cmake git mpv freetype2 pkg-config || brew link --overwrite python@3.11
      - name: Build ImPlay
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=RELEASE ..
          cmake --build . --target package
      - uses: actions/upload-artifact@v3
        with:
          name: ImPlay-macOS
          path: build/ImPlay-*.dmg
  win:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: >-
            base-devel
            git
            p7zip
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-freetype
          update: true
      - name: Build ImPlay
        shell: msys2 {0}
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=RELEASE ..
          cmake --build . --target package
      - uses: actions/upload-artifact@v3
        with:
          name: ImPlay-win64
          path: |
            build/ImPlay-*.msi
            build/ImPlay-*.zip
  publish:
    needs: [linux, macos, win]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: continuous
          force_push_tag: true
      - uses: ncipollo/release-action@v1
        with:
          commit: ${{ github.sha }}
          tag: continuous
          artifacts: "ImPlay-linux/*,ImPlay-macOS/*,ImPlay-win64/*"
          allowUpdates: true
          prerelease: true
          name: Continuous build
          body: |
            # Install
            ## Windows
            - MSI
              - Download `ImPlay-win64.msi`
              - Run the MSI
              - Run ImPlay from Start Menu
            - Zip
              - Download `ImPlay-win64.zip`
              - Extract the zip
              - Run `ImPlay.exe`
            ## macOS
            - Download `ImPlay-macOS.dmg`
            - Double click the dmg to show it's contents
            - Drag the application to Applications
            - Run ImPlay from Launchpad
            ## Linux
            - Debian Package
              - Download `ImPlay-linux64.deb`
              - Install: `sudo apt install ./ImPlay-linux64.deb`
              - Run `ImPlay`
            - AppImage
              - Download `ImPlay-linux64.AppImage`
              - Run `chmod u+x ImPlay-linux64.AppImage && ./ImPlay-linux64.AppImage`

